steps:
- id: 'Build build-container'
  name: 'gcr.io/cloud-builders/docker'
  args: [
          'build', 
          '-t', 
          'gcr.io/script-languages/build-container', 
          'google-cloud-build/ci-scripts/'
          ]
- id: 'Build images'
  name: 'gcr.io/script-languages/build-container'
  args: [
          'bash', 
          'google-cloud-build/ci-scripts/build.sh', 
          '${_FLAVOR}'
          ]
- id: 'Check build'
  name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: "bash"
  args: [
          'google-cloud-build/ci-scripts/check_build.sh', 
          "${_LOG_BUCKET}", 
          "${_FLAVOR}", 
          "$BUILD_ID"
          ]
- id: 'Run tests'
  name: 'gcr.io/script-languages/build-container'
  args: [
          'bash', 
          'google-cloud-build/ci-scripts/test.sh', 
          '${_FLAVOR}'
          ]
- id: 'Check tests'
  name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: "bash"
  args: [
          'google-cloud-build/ci-scripts/check_build.sh', 
          '${_LOG_BUCKET}', 
          '${_FLAVOR}', 
          '$BUILD_ID'
          ]
- id: 'Decrypt Docker password'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args: [
          '-x',
          'google-cloud-build/ci-scripts/decrypt.sh',
          '${_DOCKER_PASSWORD}',
          'DOCKER_PASSWORD',
          '${_KEY_RING_NAME}',
          '${_KEY_NAME}'
          ]
- id: 'Upload exported container'
  name: gcr.io/cloud-builders/gsutil
  args: [
          'cp',
          '.build_output/exports/*',
          '${_CONTAINER_BUCKET}/build_output/${_FLAVOR}/$BUILD_ID/'
          ]
timeout: "7200s"
options:
 machineType: 'N1_HIGHCPU_8'
 diskSizeGb: "50"
